- name: "Ensure all autofs services are enabled to start at boot"
  ansible.builtin.service:
    name: "{{ service_name }}"
    enabled: true
  become: true
  become_user: root
  loop: "{{ autofs_service_enable_names }}"
  loop_control:
    loop_var: service_name

- name: "Ensure all autofs services are started"
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: started
  become: true
  become_user: root
  loop: "{{ autofs_service_start_names }}"
  loop_control:
    loop_var: service_name

