- name: "Run all role tasks for Ubuntu"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    autofs_auto_master_path: "{{ autofs_linux_auto_master_path }}"
    autofs_device_mounting_template_path: "{{ autofs_linux_device_mounting_template_path }}"
    autofs_nfs_share_mounting_template_path: "{{ autofs_linux_nfs_share_mounting_template_path }}"
    autofs_device_mounting_options: "{{ autofs_linux_device_mounting_options }}"
    autofs_nfs_share_mounting_options: "{{ autofs_linux_nfs_share_mounting_options }}"
    autofs_service_names: "{{ autofs_linux_service_names }}"
    autofs_conflict_package_uninstall_list: "{{ autofs_ubuntu_conflict_package_uninstall_list }}"
    autofs_main_package_name: "{{ autofs_ubuntu_main_package_name }}"
    autofs_exfat_filesystems_package_list: "{{ autofs_ubuntu_exfat_filesystems_package_list }}"
    autofs_ntfs_filesystems_package: "{{ autofs_ubuntu_ntfs_filesystems_package }}"
    autofs_ext2_ext4_filesystems_package: "{{ autofs_ubuntu_ext2_ext4_filesystems_package }}"
    autofs_hfs_filesystems_package: "{{ autofs_ubuntu_hfs_filesystems_package }}"
    autofs_xfs_filesystems_package: "{{ autofs_ubuntu_xfs_filesystems_package }}"
    autofs_mtp_filesystems_package: "{{ autofs_ubuntu_mtp_filesystems_package }}"
  when: ansible_distribution == "Ubuntu"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    autofs_auto_master_path: "{{ autofs_freebsd_auto_master_path }}"
    autofs_device_mounting_template_path: "{{ autofs_freebsd_device_mounting_template_path }}"
    autofs_nfs_share_mounting_template_path: "{{ autofs_freebsd_nfs_share_mounting_template_path }}"
    autofs_device_mounting_options: "{{ autofs_freebsd_device_mounting_options }}"
    autofs_nfs_share_mounting_options: "{{ autofs_freebsd_nfs_share_mounting_options }}"
    autofs_service_names: "{{ autofs_freebsd_service_names }}"
    autofs_conflict_package_uninstall_list: "{{ autofs_freebsd_conflict_package_uninstall_list }}"
    autofs_main_package_name: "{{ autofs_freebsd_main_package_name }}"
    autofs_exfat_filesystems_package_list: "{{ autofs_freebsd_exfat_filesystems_package_list }}"
    autofs_ntfs_filesystems_package: "{{ autofs_freebsd_ntfs_filesystems_package }}"
    autofs_ext2_ext4_filesystems_package: "{{ autofs_freebsd_ext2_ext4_filesystems_package }}"
    autofs_hfs_filesystems_package: "{{ autofs_freebsd_hfs_filesystems_package }}"
    autofs_xfs_filesystems_package: "{{ autofs_freebsd_xfs_filesystems_package }}"
    autofs_mtp_filesystems_package: "{{ autofs_freebsd_mtp_filesystems_package }}"
  when: ansible_os_family == "FreeBSD"

