- name: "Restart all autofs services"
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: restarted
  become: true
  become_user: root
  loop: "{{ autofs_service_start_names }}"
  loop_control:
    loop_var: service_name
  listen: restart_autofs_services

