- name: "Uninstall other device auto-mounters"
  ansible.builtin.include_tasks: uninstall_other/main.yml
  when: autofs_remove_other_device_auto_mounters and
        autofs_enable_auto_device_mounting

- name: "Configure device auto-mounting"
  ansible.builtin.include_tasks: device_mounting/main.yml

- name: "Configure NFS share auto-mounting"
  ansible.builtin.include_tasks: nfs_mounting/main.yml

- name: "Configure autofs service"
  ansible.builtin.include_tasks: service/main.yml

